import React, { useState } from 'react';
import SearchStyle from './Search.module.css'

/**
 * 
 * @param {Function} callback - Holds the searchTerm generated by the handleChange fn to be fired on button click  
 * @returns Input and button JSX elements
 */
function Search({ handleClick }) {
  const [searchTerm, setSearchTerm] = useState('');

  /* Here we capture the event from the input field, I've tried to reset it to blank after the request but couldn't figure how.  */
  function handleChange(e) {
    setSearchTerm(e.target.value);
  };

  return (
    <div className={SearchStyle.container}>
      <input className={SearchStyle.input}
        type="text"
        placeholder="Search for news"
        /* Here we define the initial value of the input so it doesn't become undefined */
        value={searchTerm}
        onChange={handleChange}
      />
      {/* Here we fire the fn received as props onClick  */}
      <button onClick={() => handleClick(searchTerm)} >Search</button>
    </div>
  );
};

export default Search;
